### ISSUE TITLE
Change Dockerfiles to use local directories instead of hardcoded git repos

### ISSUE THREAD

**Issue by k3d3** [GRVYDEV/Lightspeed-ingest#20]
Hey,

I've noticed that the dockerfiles are all installing git into their containers and then using it to grab these repos from github.

Instead, they should be using something like `COPY . .` to copy the current directory (containing the Dockerfile, minus anything in .dockerignore).

The main reason is to support development within docker much easier, as code can be changed locally with images immediately rebuilt.

This is also important, however, to be able to lock down to specific versions of the code. As is, if I cloned a repo at an older commit (e.g. for debugging), I would still end up building a container with the latest code.

**Comment by GRVYDEV** [comment]
Hi! Thank you for this insight! As of right now Lightspeeds docker support is... shall I say "experimental" and will be changing a lot over the coming weeks. My plan is to create docker images on tagged commits and then pull those from the main repo. I will, however take this into mind because I do want to support docker for those actively developing Lightspeed!

**Comment by k3d3** [comment]
No worries! I'm about to make some PRs in relation to the docker support actually, and this is mostly just as documentation.

**Comment by GRVYDEV** [comment]
> No worries! I'm about to make some PRs in relation to the docker support actually, and this is mostly just as documentation.

Thank you! Would you be willing to add those changes to the other repositories?

**Comment by k3d3** [comment]
Sure thing!
